[build]
  publish = "public"
  command = "npm run export:netlify"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/question-answer/PART*"
  to = "/question-answer/detail.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
